### ISSUE TITLE
multitouch issues.

### ISSUE THREAD

**Issue by stodag** [PatrikKT/android_kernel_huawei_y550#1]
hi m8, sry for postin here but i was havin trouble over at xda. anyway, theres a multitouch issue on stock aswell as cm 11 just wondered if youd have a look with an multitouch tester app. thanks and great work, id donate if it helps.

**Comment by stodag** [comment]
mainly noticable in fps.. yes im a gamer:) cheers

**Comment by PatrikKT** [comment]
Thank you for reporting. Could you, please, send me your /proc/app_info file? You can post it either here or send it via email to 123patokt@gmail.com.

**Comment by PatrikKT** [comment]
Issue not related to kernel. Happens with M-Star touchscreen. These kind of issues can be expected on such a cheap phone.
